[package]
name = "github-meiliserarch"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
meilisearch-sdk = "0.24.3"
octocrab = "0.33.1"
tokio = { version = "1.35.1", features = ["rt", "rt-multi-thread", "macros"] }
indicatif = "0.17.7"
serde = { version = "1.0.195", features = ["derive"] }
